export { default as Navbar } from './navbar'
export { default as Home } from './home'
export { default as About } from './about'
export { default as Skills } from './skills'
export { default as Projects } from './projects'
export { default as Contact } from './contact'
export {default as Footer} from './footer'
